### ISSUE TITLE
Question on Figure 2 in your paper

### ISSUE THREAD

**Issue by gpengzhi** [neulab/awesome#51]
![6a73254d1c20528d75da5730ddb28c44](https://user-images.githubusercontent.com/16913241/210517171-4616dd82-1648-46a2-8c04-3d7de39344ca.png)

In the intersection matrix, why is the entry pointed out to be one?

Do I miss some technical details?

Thanks a lot!

**Comment by gpengzhi** [comment]
Another question:

When you apply self-training objective, the alignment matrix A is not the bpe-level intersection 0-1 matrix(?) The alignment matrix A you used is actually the word-level alignment 0-1 matrix converted from the bpe-level intersection matrix. It that correct?

**Comment by zdou0830** [comment]
Thanks for the questions!

`why is the entry pointed out to be one?`

this is because some entries got rounded down to 0 in the visualization but they are actually greater than the threshold (i.e. they are in the range [0.001, 0.005]).

`the alignment matrix A`

correct. I remembered that I found using word-level alignment is better for most language pairs.
